import type { Metadata } from 'next';
import './globals.scss';
import Outro from '@/components/Outro';

export const metadata: Metadata = {
    title: "Gopi's Portfolio",
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                <main className="layout">{children}</main>
                <Outro />
            </body>
        </html>
    );
}
