import type { Metadata } from 'next';
import './globals.scss';

export const metadata: Metadata = {
    title: "Gopi's Portfolio",
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <head>
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/FortAwesome/Font-Awesome@5.15.4/css/all.min.css" />
            </head>
            <body>
                <main className="layout">{children}</main>
            </body>
        </html>
    );
}
