import { AccordionProps } from '@/components/Accordion';
import { ProjectLableProps } from '@/components/Projects/ProjectLabel';
import CircleLogo from '@assets/images/circle_dna_logo.jpeg';

export enum Projects {
    CircleWebsite = 'CircleWebsite',
    CircleMobile = 'CircleMobile',
}

export interface ProjectDataType {
    projectLabel: ProjectLableProps;
    accordionContents: AccordionProps[];
}

export const projectDataMap: Record<Projects, ProjectDataType> = {
    [Projects.CircleWebsite]: {
        projectLabel: {
            image: CircleLogo,
            title: 'CircleDNA Marketing Website (D2C)',
            employer: 'Prenetics',
            technology: 'Next.js, TypeScript, Node.js, PostgreSQL, API, Express.js and AWS',
        },
        accordionContents: [
            {
                id: `${Math.floor(Math.random() * 10000 + 1)}`,
                name: 'list',
                label: 'Website Development',
                content: [
                    'Developed the CircleDNA marketing e-commerce website using Next.js (React) and TypeScript, providing a responsive and engaging online platform for users to purchase DNA collection kits.',
                ],
                hasContentPadding: true,
                topBorderOnly: true,
                withShadow: false,
            },
            {
                id: `${Math.floor(Math.random() * 10000 + 1)}`,
                name: 'list',
                label: 'E-Commerce Functionality',
                content: ['Implemented e-commerce features such as product listing, shopping cart, product details, and secure user account management, ensuring a seamless purchasing experience.'],
                hasContentPadding: true,
                topBorderOnly: true,
                withShadow: false,
            },
            {
                id: `${Math.floor(Math.random() * 10000 + 1)}`,
                name: 'list',
                label: 'Internationalization (i18n)',
                content: [
                    "Implemented internationalization features to support multiple languages, allowing users from various regions to access the website in their preferred language. This involved the translation of content, user interface elements, and product descriptions, enhancing the website's accessibility and user engagement for a diverse global audience.",
                ],
                hasContentPadding: true,
                topBorderOnly: true,
                withShadow: false,
            },
            {
                id: `${Math.floor(Math.random() * 10000 + 1)}`,
                name: 'list',
                label: 'Stripe Payment Integration',
                content: ['Integrated Stripe payment solutions to enable secure and efficient online payments, ensuring a smooth checkout process for customers.'],
                hasContentPadding: true,
                topBorderOnly: true,
                withShadow: false,
            },
            {
                id: `${Math.floor(Math.random() * 10000 + 1)}`,
                name: 'list',
                label: 'SEO Optimization',
                content: ["Implemented search engine optimization (SEO) techniques to improve the website's visibility and search engine rankings."],
                hasContentPadding: true,
                topBorderOnly: true,
                withShadow: false,
            },
            {
                id: `${Math.floor(Math.random() * 10000 + 1)}`,
                name: 'list',
                label: 'Performance Optimization',
                content: [
                    'Employed various performance optimization strategies, including code splitting, lazy loading, and image optimization, to enhance website speed and responsiveness, resulting in a better user experience.',
                ],
                hasContentPadding: true,
                topBorderOnly: true,
                withShadow: false,
            },
            {
                id: `${Math.floor(Math.random() * 10000 + 1)}`,
                name: 'list',
                label: 'TypeScript Implementation',
                content: ['Leveraged TypeScript to enhance code quality, and maintainability, and to catch potential issues at compile-time, making the codebase more robust.'],
                hasContentPadding: true,
                topBorderOnly: true,
                withShadow: false,
            },
            {
                id: `${Math.floor(Math.random() * 10000 + 1)}`,
                name: 'list',
                label: 'Node.js Backend Integration',
                content: ['Collaborated with the backend development team to integrate the website with the Node.js backend, ensuring smooth data exchange and e-commerce functionality'],
                hasContentPadding: true,
                topBorderOnly: true,
                withShadow: false,
            },
            {
                id: `${Math.floor(Math.random() * 10000 + 1)}`,
                name: 'list',
                label: 'User Account Management',
                content: ['Implemented user account functionality, allowing customers to create and manage their accounts, view order history, and track their DNA kit shipments.'],
                hasContentPadding: true,
                topBorderOnly: true,
                withShadow: false,
            },
            {
                id: `${Math.floor(Math.random() * 10000 + 1)}`,
                name: 'list',
                label: 'Product Management',
                content: [
                    'Worked with the product team to manage product listings, including descriptions, images, pricing, and availability, keeping the website up-to-date with the latest offerings.',
                ],
                hasContentPadding: true,
                topBorderOnly: true,
                withShadow: false,
            },
            {
                id: `${Math.floor(Math.random() * 10000 + 1)}`,
                name: 'list',
                label: 'Responsive Design',
                content: ['Ensured that the website was responsive and accessible on various devices and screen sizes, accommodating a broad range of users.'],
                hasContentPadding: true,
                topBorderOnly: true,
                withShadow: false,
            },
            {
                id: `${Math.floor(Math.random() * 10000 + 1)}`,
                name: 'list',
                label: 'Cross-Browser Compatibility',
                content: ['Tested and ensured that the website functioned correctly on different web browsers to provide a consistent experience for all users.'],
                hasContentPadding: true,
                topBorderOnly: true,
                withShadow: false,
            },
            {
                id: `${Math.floor(Math.random() * 10000 + 1)}`,
                name: 'list',
                label: 'Continuous Integration and Deployment',
                content: ['Implemented CI/CD pipelines to automate the deployment process, making it easier to roll out updates and new features with the help of AWS.'],
                hasContentPadding: true,
                topBorderOnly: true,
                withShadow: false,
            },
            {
                id: `${Math.floor(Math.random() * 10000 + 1)}`,
                name: 'list',
                label: 'Monitoring and Analytics',
                content: ['Set up monitoring tools and analytics to track user behavior, website performance, and e-commerce metrics, enabling data-driven improvements.'],
                hasContentPadding: true,
                topBorderOnly: true,
                withShadow: false,
            },
            {
                id: `${Math.floor(Math.random() * 10000 + 1)}`,
                name: 'list',
                label: 'Bug Fixing and Maintenance',
                content: ['Conducted regular maintenance and troubleshooting to identify and address software defects and maintain a stable website.'],
                hasContentPadding: true,
                topBorderOnly: true,
                withShadow: false,
            },
            {
                id: `${Math.floor(Math.random() * 10000 + 1)}`,
                name: 'list',
                label: 'Documentation',
                content: ['Maintained thorough code documentation to facilitate collaboration with team members and future maintenance.'],
                hasContentPadding: true,
                topBorderOnly: true,
                withShadow: false,
            },
            {
                id: `${Math.floor(Math.random() * 10000 + 1)}`,
                name: 'list',
                label: 'Security Compliance',
                content: ["Ensured the website's security by implementing best practices for data protection and e-commerce security standards."],
                hasContentPadding: true,
                topBorderOnly: true,
                withShadow: false,
            },
        ],
    },
    [Projects.CircleMobile]: {
        projectLabel: {
            image: CircleLogo,
            title: 'CircleDNA Mobile App (D2C)',
            employer: 'Prenetics',
            technology: 'React Native, TypeScript, Expo, REST API and AWS',
        },
        accordionContents: [
            {
                id: `${Math.floor(Math.random() * 10000 + 1)}`,
                name: 'list',
                label: 'Mobile Application Development',
                content: ['Developed the CircleDNA mobile application using React Native and TypeScript, ensuring a smooth and responsive user experience on both iOS and Android platforms.'],
                hasContentPadding: true,
                topBorderOnly: true,
                withShadow: false,
            },
            {
                id: `${Math.floor(Math.random() * 10000 + 1)}`,
                name: 'list',
                label: 'User Authentication',
                content: [
                    'Implemented various screens and components for user authentication, including login, registration, and password reset functionalities, ensuring a secure and user-friendly authentication process.',
                ],
                hasContentPadding: true,
                topBorderOnly: true,
                withShadow: false,
            },
            {
                id: `${Math.floor(Math.random() * 10000 + 1)}`,
                name: 'list',
                label: 'Report Viewing',
                content: [
                    'Designed and developed the report viewing feature, enabling users to access and interact with their DNA health reports. Ensured that the reports were displayed accurately and in a user-friendly manner.',
                ],
                hasContentPadding: true,
                topBorderOnly: true,
                withShadow: false,
            },
            {
                id: `${Math.floor(Math.random() * 10000 + 1)}`,
                name: 'list',
                label: 'Product Integration',
                content: [
                    "Collaborated with the product team to integrate and display CircleDNA's products and services within the app. Implemented features for users to explore and purchase these products.",
                ],
                hasContentPadding: true,
                topBorderOnly: true,
                withShadow: false,
            },
            {
                id: `${Math.floor(Math.random() * 10000 + 1)}`,
                name: 'list',
                label: 'TypeScript Integration',
                content: ['Utilized TypeScript to enhance the codebase by adding static typing, which improved code quality, maintained code consistency, and reduced runtime errors.'],
                hasContentPadding: true,
                topBorderOnly: true,
                withShadow: false,
            },
            {
                id: `${Math.floor(Math.random() * 10000 + 1)}`,
                name: 'list',
                label: 'Cross-Platform Compatibility',
                content: ['Ensured that the mobile app worked seamlessly on both iOS and Android devices, optimizing the user interface for various screen sizes and resolutions'],
                hasContentPadding: true,
                topBorderOnly: true,
                withShadow: false,
            },
            {
                id: `${Math.floor(Math.random() * 10000 + 1)}`,
                name: 'list',
                label: 'Node.js Backend Integration',
                content: ['Collaborated with the backend development team to integrate the mobile app with the Node.js backend. Implemented API calls and data exchange to support app functionality'],
                hasContentPadding: true,
                topBorderOnly: true,
                withShadow: false,
            },
            {
                id: `${Math.floor(Math.random() * 10000 + 1)}`,
                name: 'list',
                label: 'UI/UX Design Collaboration',
                content: ['Worked closely with the design team to implement visually appealing and intuitive user interfaces, maintaining a consistent design language throughout the app.'],
                hasContentPadding: true,
                topBorderOnly: true,
                withShadow: false,
            },
            {
                id: `${Math.floor(Math.random() * 10000 + 1)}`,
                name: 'list',
                label: 'Performance Optimization',
                content: ['Implemented performance optimizations to ensure fast load times, smooth animations, and efficient data fetching, resulting in a positive user experience'],
                hasContentPadding: true,
                topBorderOnly: true,
                withShadow: false,
            },
            {
                id: `${Math.floor(Math.random() * 10000 + 1)}`,
                name: 'list',
                label: 'Bug Fixing and Maintenance',
                content: ['Conducted debugging and troubleshooting to identify and fix software defects, ensuring a stable and reliable mobile application.'],
                hasContentPadding: true,
                topBorderOnly: true,
                withShadow: false,
            },
            {
                id: `${Math.floor(Math.random() * 10000 + 1)}`,
                name: 'list',
                label: 'Code Documentation',
                content: ['Maintained thorough code documentation to make it easier for other developers to understand and contribute to the project.'],
                hasContentPadding: true,
                topBorderOnly: true,
                withShadow: false,
            },
            {
                id: `${Math.floor(Math.random() * 10000 + 1)}`,
                name: 'list',
                label: 'Version Control',
                content: ['Utilized version control systems such as Git to manage code changes, collaborate with team members, and track project progress.'],
                hasContentPadding: true,
                topBorderOnly: true,
                withShadow: false,
            },
            {
                id: `${Math.floor(Math.random() * 10000 + 1)}`,
                name: 'list',
                label: 'Testing and Quality Assurance',
                content: ["Participated in testing and quality assurance efforts to identify and resolve issues, ensuring the app's overall quality and reliability"],
                hasContentPadding: true,
                topBorderOnly: true,
                withShadow: false,
            },
            {
                id: `${Math.floor(Math.random() * 10000 + 1)}`,
                name: 'list',
                label: 'User Feedback Integration',
                content: ["Collaborated with the product team to incorporate user feedback and enhance the app's functionality and usability."],
                hasContentPadding: true,
                topBorderOnly: true,
                withShadow: false,
            },
            {
                id: `${Math.floor(Math.random() * 10000 + 1)}`,
                name: 'list',
                label: 'Security Compliance',
                content: ["Ensured the app's security by implementing best practices for user data protection and authentication, complying with industry standards and regulations"],
                hasContentPadding: true,
                topBorderOnly: true,
                withShadow: false,
            },
        ],
    },
};
